#Web基础配置
server:
  port: 8080
  servlet:
    context-path: /redisDemo

#Spring组件配置
spring:
#  Redis参数配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password: redis
    timeout: 100000
#    使用jedis中间件并配置
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
